baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

paginate = 2

[params]
    dateFormat = "Jan 2, 2006"

[taxonomies]
    category = "categories"
    author = "authors"

